#spring:
#  application:
#    name: integration
spring:
  cloud:
    openfeign:
      httpclient:
        disable-ssl-validation: true
        enabled: false
      okhttp:
        enabled: true

app:
#  integration-1c-client: